openapi: 3.0.3
info:
  title: Product API
  description: API for retrieving product and novelty information.
  version: 1.0.0
paths:
  /products:
    get:
      summary: Retrieve a list of products
      description: Returns a list of products with their details.
      responses:
        '200':
          description: A list of products.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    productName:
                      type: string
                      example: Product Item 1
                    price:
                      type: integer
                      example: 500
                    productCode:
                      type: string
                      example: PRD001
                    caption:
                      type: string
                      example: A reliable product for everyday use.
  /novelties:
    get:
      summary: Retrieve a list of novelties
      description: Returns a list of novelty items with their details.
      responses:
        '200':
          description: A list of novelty items.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    productName:
                      type: string
                      example: Novelty Item 1
                    price:
                      type: integer
                      example: 1000
                    productCode:
                      type: string
                      example: NOV001
                    caption:
                      type: string
                      example: A great novelty item for your collection.
servers:
  - url: https://api.example.com
    description: Mock server
